bind_addr = ":9000"
log_level = "debug"
database_url = "host=localhost user=zima password=postgres port=5433 dbname=restapi_dev sslmode=disable"
session_key = "V+ZgTOs5fKLbrF2wS3HHGqXgeipU+FBYb5i33T/sSq0="